### ISSUE TITLE
任意文件下载上传

### ISSUE THREAD

**Issue by CreeperGo** [Rubiginosu/frozen-go#4]
https://github.com/Rubiginosu/frozen-go/blob/master/daemon/src/filetrans/handle.go
处理上传下载指令时未过滤c.args导致【有服务器文件上下传权限】的用户任意读写文件
例如c.args="../../../../../bin/ping"
如果fgo以高权限运行可能造成主机被提权
同时建议fgo应该采取限制自身权限的措施例如强制低权限账户运行

**Comment by Axoford12** [comment]
我只有晚上补了，你有空就先补着吧。

**Comment by Axoford12** [comment]
呐，补好了
