### ISSUE TITLE
SDK need long connection and UNIX socket

### ISSUE THREAD

**Issue by CreeperGo** [Rubiginosu/frozen-go#8]
frozen-go/SDK/FrozenGo.php
FrozenGo::SockResult
建议使用tcp长连接，或者unix socket（推荐后者）
频繁建立连接会加重daemon负载
关键是用完了根本没关闭socket。。。这样如果高并发会出问题的

**Comment by Axoford12** [comment]
使用短链接的原因是，panel是php写的。php用长连接就比较反人类(你懂的)而且搞起来最后还不如短链接

**Comment by CreeperGo** [comment]
建议如果daemon和panel同一个机子的话，使用UNIX Socket

**Comment by Axoford12** [comment]
问题是不同机啊，多个daemon对应一个panel，如果这个daemon用Unix socket 那个daemon又用短链接，岂不是让php开发者觉得反人类？

**Comment by Axoford12** [comment]
如果用长连接，就涉及php超时时间啊什么鬼的，况且情况复杂多变，用户随时都可能请求，如果间隔过长就意味着超时。那就会出很多很多蜜汁bug，panel也不知道什么时候要用这个接口那个接口，所以不采用长连接or Unix socket
